"""Add code and code hash

Revision ID: 3d713e047fbc
Revises: 5fb80aed502e
Create Date: 2024-07-22 23:07:00.797674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d713e047fbc'
down_revision: Union[str, None] = '5fb80aed502e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_account', sa.Column('code', sa.String(length=10), nullable=True))
    op.add_column('telegram_account', sa.Column('code_hash', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_account', 'code_hash')
    op.drop_column('telegram_account', 'code')
    # ### end Alembic commands ###
