"""define nullable

Revision ID: 5fb80aed502e
Revises: d0d4b73e4fe7
Create Date: 2024-07-21 15:54:40.974573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fb80aed502e'
down_revision: Union[str, None] = 'd0d4b73e4fe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('telegram_account', 'cleared',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('telegram_account', 'sold',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('telegram_account', 'sold',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('telegram_account', 'cleared',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
